build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-blink"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-dsp"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-events"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-rtos"
    - PLATFORMIO_PROJECT_DIR: "examples/mbed-serial"

install:
  - cmd: git submodule update --init --recursive
  - cmd: SET PATH=C:\Python36\Scripts;%PATH%
  - cmd: pip3 install -U https://github.com/platformio/platformio/archive/develop.zip
  - cmd: platformio platform install file://.

test_script:
  - cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%
